### ISSUE TITLE
Can WFS Search work with geoJSON?

### ISSUE THREAD

**Issue by gkvoelkl** [terrestris/react-geo#1071]
Hello,

I am a react newbie and try to use WFS Search. Can WFS Search work with an WFS-Service that reaturns geoJSON?

```
 <WfsSearch
                key='search' 
                placeholder='Suche..'
                baseUrl='/mapserver/cgi-bin/mapserv?map=/data/ows/maps/strassennamen.map'
                featureTypes={['strassennamen']}
                srsName="EPSG:4326"    
                outputFormat='geojson'
                searchAttributes={{
                    'strassennamen':['SUCH_STRING'] 
                }}              
                map ={map}  
              />
```
WFS returns geoJSON and than something went wrong.

Any hint?

Thanks.

**Comment by hwbllmnn** [comment]
I think this is mostly tested with GeoJSON. What kind of errors are you getting? What WFS are you using, and can you give an example GeoJSON output?

**Comment by gkvoelkl** [comment]
The only error in console window was

```
Error while requesting WFS GetFeature: Error: Invalid `value` of type `undefined` supplied to Option, expected `string` when `tags/combobox` is `true`. index.js:1446

onFetchError WfsSearch.js:380
```
I created myself the WFS-service with mapserver. It's a project for a customer, so I can't publish an example file.

**Comment by hwbllmnn** [comment]
Perhaps you need a namespace prefix in the feature type name? That should probably be the same prefix than the one used in the GML output of the WFS. Also, are you sure the attribute is all uppercase in the GeoJSON? Does the attribute contain null values for some features?

**Comment by gkvoelkl** [comment]
The GeoJSON file I get back from the WFS-server looks like that

Here an anonymous example

```
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "LABEL_TEXT": "Teststraße", "SUCH_STRING": "TESTSTRASSE" }, "geometry": { "type": "Point", "coordinates": [ 1, 2 ] } },
..
]
}
```

**Comment by hwbllmnn** [comment]
Ah, you need to configure a value for the `displayValue` prop. By default it has the value `'name'`, and your feature type doesn't have that attribute. Use `displayValue='LABEL_TEXT'` for example.

**Comment by gkvoelkl** [comment]
That's the solution.

Thanks.
