### ISSUE TITLE
Examples in documentation not working

### ISSUE THREAD

**Issue by jansule** [terrestris/react-geo#1072]
The examples in the [docs](https://terrestris.github.io/react-geo/docs/latest/index.html) are not working. Following error is shown:

```
Error: import or require() statements can be added only by editing a Markdown example file: ol/Map
```

**Comment by dnlkoch** [comment]
Thanks for the report @jansule.

I fixed this by updating the `gh-pages` branch with a local build of the styleguide. Not sure why, but the styleguide build on travis is broken. See #1074 for a quick fix.
