### ISSUE TITLE
WfsSearch define id column

### ISSUE THREAD

**Issue by gkvoelkl** [terrestris/react-geo#1097]
In WfsSearch I can define the displayed value

` displayValue='LABEL_TEXT' `

I there a way to define the name of the id column ?

At the moment it is 'id'

**Comment by marcjansen** [comment]
If there isn't a way, we probably should have one... @kaivolland or @dnlkoch, can you shed a light?

**Comment by KaiVolland** [comment]
This is currently not possible. I'll add it.

**Comment by dnlkoch** [comment]
Thanks @gkvoelkl for posting this issue, it is fixed and is now available via version [11.3.0](https://github.com/terrestris/react-geo/releases/tag/v11.3.0).

**Comment by marcjansen** [comment]
Thanks everybody!
