### ISSUE TITLE
MapProvider Promise is undefined IE11

### ISSUE THREAD

**Issue by gkvoelkl** [terrestris/react-geo#1113]
With IE11 my web-app starts with error "Promise is undefined" in MapProvider.js
It's in runtime environment after build.

```
_defineProperty(MapProvider, "propTypes", {
  /**
   * The children of the MapProvider.
   * @type {Object}
   */
  children: _propTypes["default"].node,

  /**
   * The map can be either an OlMap or a Promise that resolves with an OlMap
   * if your map is created asynchronously.
   *
   * @type {ol.Map|Promise}
   */
```
In chrome there is no error in my runtime environment.

In development environment all works well with firefox. (There is no IE at the moment.)

**Comment by hwbllmnn** [comment]
Try including the npm package `promise-polyfill` in your application.

**Comment by gkvoelkl** [comment]
I installed the package 

`npm install promise-polyfill --save-exact`

I got the same error.

Do I have to include the new package in my programm text, too?
Any includes? Any new commands?

**Comment by hwbllmnn** [comment]
You should include that in your own application, yes. If that doesn't work, try loading the polyfill manually before anything else in your `index.html` (or whatever html file you're using).

**Comment by dnlkoch** [comment]
Yes, you need to include it into your bundler configuration. If you use `webpack` you may can use [this](https://github.com/terrestris/react-geo-baseclient/blob/master/packages/baseclient/config/webpack.common.config.js#L28) as a starting point.

**Comment by gkvoelkl** [comment]
I included it in  index.html. That works.
`    <script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>`

I think it is better to change webpack configuration. 

I startet with react only some weeks ago and did not find the file webpack.common.config.js in my files.

Thanks.

**Comment by gkvoelkl** [comment]
In index.js  as first line

```
import 'react-app-polyfill/ie9';
import 'core-js/fn/array/find';
```
is my current solution.
