### ISSUE TITLE
openlayers 6?

### ISSUE THREAD

**Issue by steam0r** [terrestris/react-geo#1128]
hey,

i am starting a new map project and would love to use this library, are there any plans
on supporting openlayers 6 in this? would this take a lot of porting? a quick try gave
me just a 50% map in size, while ol 5 showed up in full width...would it be woth fixing this
or will i encounter a lot more incompatibilities down the line?

thanks for your answer!

**Comment by marcjansen** [comment]
It is likely that we'll support OL 6 once we have it. Speaking of it, we might want to create a branch that tries to work against the master of OpenLayers. @steam0r do you mind sharing your efforts so far?

I can neither give an estimate of effort nor an expected date when we'll have support, but I for sure want it.

HTH

**Comment by steam0r** [comment]
this seems to be a changelog for 6.0:

https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md

**Comment by marcjansen** [comment]
There is quite a bit of work, nonetheless I think support will be easier than e.g. going from 4 to 5. Thanks for the pointer.

**Comment by KaiVolland** [comment]
Solved with #1231
