### ISSUE TITLE
many maps in the same page

### ISSUE THREAD

**Issue by cpfreitas** [terrestris/react-geo#1142]
Can I put more than one map component in the same page? How?
Thanks

**Comment by dnlkoch** [comment]
Yes, this should be possible by passing the appropriate ol map via the `map` prop alongside with an unique identifier (`mapDivId`) the [MapComponent](https://terrestris.github.io/react-geo/docs/latest/index.html#mapcomponent) like this:

```
// somewhere in your application
const map1 = new OlMap({…});
const map2 = new OlMap({…});

(…)

// in render():
<MapComponent
  map={map1}
  mapDivId="map1"
/>
<MapComponent
  map={map2}
  mapDivId="map2"
/>
```
