### ISSUE TITLE
Unused (?) packages

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#1239]
I checked the package.json and found some packages that were not directly used elsewhere. We should check if these can be removed:

- loglevel
- react-dom-factories
- shp-js
- url-parse
- validator
- @babel/cli (I don't think we use babel via command line)
- react-test-renderer
- regenerator-runtime

**Comment by dnlkoch** [comment]
Removed the listed dependencies (and some others) except `babel` as it is needed in the build stage.
