### ISSUE TITLE
GeoJSON vectorlayer is not rendered

### ISSUE THREAD

**Issue by dmenneck** [terrestris/react-geo#1251]
I am experiencing an issue with OpenLayers & react-geo, where I do not know if the problem stems from OL or from react-geo.

The following code for displaying a GeoJSON layer on a basemap works in OL only.
See source code: [here](https://github.com/dmenneck/CampusMap/blob/master/OLmap/index.html)

But if I try to include this into my react-geo application, the GeoJSON layer will not be rendered and the following error message shows up:

```javascript
    Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at getObject (JSONFeature.js:216)
    at GeoJSON.readFeatures (JSONFeature.js:59)
    at VectorSource.<anonymous> (featureloader.js:91)
```

See code: [here](https://github.com/dmenneck/CampusMap/blob/master/src/components/Map.js)

**Comment by hwbllmnn** [comment]
I couldn't build your project:

```
./src/components/Infos.js
Module not found: Can't resolve '../img/kölnMap.png' in '/tmp/CampusMap/src/components'
```

But I'm guessing the path to the `buildings.json` is wrong and returns a 404 or similar error message with an HTML page (that can't be parsed as JSON). Have you tried `../buildings.json`?

**Comment by dnlkoch** [comment]
```
