### ISSUE TITLE
Remove inline Style from NominatimSearch

### ISSUE THREAD

**Issue by jansule** [terrestris/react-geo#1260]
The `NominatimSearch` component uses a default inline style which overrides css classes and forces users to use `!important`. See https://terrestris.github.io/react-geo/docs/latest/index.html#nominatimsearch

I suggest removing the default style from the component to be able to properly work with css classes

**Comment by Unraveler** [comment]
Currently the `NominatimSearch` is only setting the width

```

**Comment by dnlkoch** [comment]
Inline style is not set anymore, closing this issue.
