### ISSUE TITLE
could not load TimeLayerSliderPanel

### ISSUE THREAD

**Issue by klinucsd** [terrestris/react-geo#1288]
the following statement failed:

import { TimeLayerSliderPanel } from '@terrestris/react-geo';

checked the index.ts at https://github.com/terrestris/react-geo/blob/master/src/index.ts and seems that TimeLayerSliderPanel  is not included in the export list.

**Comment by annarieger** [comment]
Nice catch, @klinucsd! Missing export is added in #1289, fix will be available in next released version.

**Comment by annarieger** [comment]
Please check the newest react-geo release ([v13.0.1](https://github.com/terrestris/react-geo/releases/tag/v13.0.1)) for the fix.
