### ISSUE TITLE
react-geo in react-boilerplate [Question]

### ISSUE THREAD

**Issue by rsurgiewicz** [terrestris/react-geo#1585]
Hi All,

I'm struggling to get react-geo up & running in react-boilerplate-template-cra however no success:

This is my map component
```
import React from 'react';
import { useSelector, useDispatch } from 'react-redux';

import OlMap from 'ol/Map';
import OlView from 'ol/View';
import OlLayerTile from 'ol/layer/Tile';
import OlSourceOsm from 'ol/source/OSM';

import 'ol/ol.css';
import 'antd/dist/antd.css';
import './style.css';


import {
    CircleMenu,
    SimpleButton,
    MapComponent,
    MapProvider,
    mappify
  } from '@terrestris/react-geo';

interface Props {}

export function OlMapComponent(props: Props) {
  const layer = new OlLayerTile({
    source: new OlSourceOsm(),
  });

  const center = [788453.4890155146, 6573085.729161344];

  const map = new OlMap({
    view: new OlView({
      center: center,
      zoom: 16,
    }),
    layers: [layer],
  });

  return (
    <>
      <MapComponent map={map} />
    </>
  );
}
```

However no map is loaded in the end result.
I can see `<div id=map class=map ....`  in browser inspector but no map image is loaded

any tips? Thanks!

**Comment by dnlkoch** [comment]
Hi @rsurgiewicz, have you tried to set the `width` and `height` values for the `map` container to a custom value, e.g. `100%`?

You may want to check the [react-geo workshop](https://terrestris.github.io/react-geo-ws/map-integration/map-component.html) as this is a working example on how to use `react-geo` inside a `cra`.

**Comment by rsurgiewicz** [comment]
thank you @dnlkoch  I had to set css values of width and height to "vh" and "vw" settings as the map was nested in another div.

Quick question regarding `MapComponent` and updates of map.

I have map with WMS layer that I need to modify but I map does not refresh
```
layer.getSource().updateParams({
   cql_filter: "h3resolution=6 and rat='" + currentNetRat + "'",
});
layer.getSource().changed();
layer.changed();```

as well as `map.changed()`... but eventhough layers are updated (I logged dump of layer to console) map is not refreshed.

What shall be done to `MapComponent` to refresh the map?

**Comment by dnlkoch** [comment]
Usually it's sufficient to just call [updateParams()](https://openlayers.org/en/master/apidoc/module-ol_source_TileWMS-TileWMS.html#updateParams) on the layers source. Please verify, that the layer tiles will be reloaded once you forced the update. If so, please also ensure, the params have been changed otherwise the request will be cached by the browser.
