### ISSUE TITLE
Should we keep a changelog in the repository?

### ISSUE THREAD

**Issue by marcjansen** [terrestris/react-geo#1652]
This is open for discussion:

I would like to have a manually crafted [changelog](https://keepachangelog.com/en/1.1.0/). Our current [release notes](https://github.com/terrestris/react-geo/releases) are not as friendly as a single file in the repository which gets updated while PRs are coming in. The linked page also has other benefits.

Especially now with deprecations, we should keeep track of them, as they are not mentioned in the release notes.

Opinions?

**Comment by jt-helsinki** [comment]
yes, please. 

We would like to try and follow the upgrade path. A change log would be helpful.... although more work for the development team. :(

**Comment by marcjansen** [comment]
More opinions?

**Comment by simonseyock** [comment]
react-geo now uses the semantic-release plugin to automatically create releases and a changelog. It still has to be maintained, but the tools are here.
