### ISSUE TITLE
UseMap issue

### ISSUE THREAD

**Issue by scribe-maxime** [terrestris/react-geo#1777]
Hi, first of all thank you for your amazing work ! 👍 

i recently updated react-geo to the lastest version and i saw the new hook : useMap  !
after i check the exemple i wanna use it but i got some issues with it, that why i'm comming to ask for you support here ! :)

so like the exemple i create a map in a component and store it to the MapContext.provider, 

in another component i need to get the map but when i call the hook maps object seems differants ( differants ol_uid ) so maybe i used it in a bad way, or maybe it's not working properly 

thanks for your help !

**Comment by dnlkoch** [comment]
Hi @scribe-maxime, thanks for your report! I tested the current version of `react-geo` with a similar usecase, but unfortunately I couldn't reproduce your issue (see example introduced in #1846). Can you provide a minimal example?
