### ISSUE TITLE
InstanceOf / use with Standard ol

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#206]
We use the `PropTypes.instanceOf(<SOMECLASS>)` check in some classes.

I fear that this wont work with the standard ol: `OlMap` != `ol.Map`.
Do we want to support standard ol? If not we have to remove the `basicMap.html` examples...

**Comment by marcjansen** [comment]
What is now an additional module (es modules published as npm package ol) will rather sooner than later become the standard of openlayers.

How likely is it that people build a react app but include a prepared build of openlayers? I guess most will have a dedicated build process which hopefully uses the `ol` package and imports just what is needed.

So I tend to say that I think we do not need to support `ol.Map`, only `OlMap`.

**Comment by dnlkoch** [comment]
Agreed!

**Comment by KaiVolland** [comment]
This is no longer an issue as we removed all apperances of `ol.*` and we only use the package now.
