### ISSUE TITLE
InternetExplorer (examples)

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#207]
Which IE-Version do we want to support?

Currently our examples are not working in IE 11 we should fix this.

**Comment by dnlkoch** [comment]
`antd` supports ["all the modern browsers and IE9+"](https://ant.design/docs/react/getting-started#Compatibility), but requires some polyfills to work in in IE9. So I think we should try to support IE9 as well.

Nonetheless we must support IE11 definitely and should fix the examples as soon as possible.

**Comment by KaiVolland** [comment]
We need to add whatwg-fetch and maybe some more ployfills to our webpack config...

**Comment by dnlkoch** [comment]
Fixed in #504 and tested successfully in IE11.
