### ISSUE TITLE
Usage with Vite 

### ISSUE THREAD

**Issue by digoburigo** [terrestris/react-geo#2339]
Hello, I want to know if it's possible to use this library with Vite (https://vitejs.dev/)?

**Comment by hwbllmnn** [comment]
I think it has never been tried, but in theory it should work just fine, react-geo is just a react library. Let us know if something is missing.

**Comment by marcjansen** [comment]
@digoburigo just keep us updated, I used vite for smaller things and really like it.

**Comment by digoburigo** [comment]
Yeah, I managed to get to work. I'm using vite react-ts template and the types of openlayers in build mode was resolved in with `skipLibCheck: true` in the `tsconfig.json`, something that the openlayers recommends. And because the documentation of `useMap`, the code part, is not importing from the `dist` folder and that was a issue too. Thanks for the response.

![image](https://user-images.githubusercontent.com/28462822/155027624-9863d571-7e52-493f-bc12-6bb7209a49d6.png)
