### ISSUE TITLE
Switch to styled components

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#236]
We should think about switching to styled components instead of less.

This would fix the requirement of a less-loader (#225) and would add more flexibility to the styles.

**Comment by dnlkoch** [comment]
Generally speaking I totally agree to make use of [styled components](https://www.styled-components.com/) where possible, but I'm a little bit curious if we could (and want) to get rid of less in the library. Could you provide an example to start a technical discussion on this?

**Comment by KaiVolland** [comment]
The effort is would be quite big i think. So i'll close this for now.
