### ISSUE TITLE
MeasureButton bugs

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#266]
~~1. Each button creates an own measurelayer. We should check if the map allready contains a measurelayer.~~
1. Multiple Drawing doesn't act as expected. --> Tooltips disapper
1. Check if Tooltip could be an seperate component.

**Comment by marcjansen** [comment]
Can we still reproduce this, or even better, fix this?

**Comment by dnlkoch** [comment]
Yes, it's still an issue.
