### ISSUE TITLE
Update WfsSearch documentation.

### ISSUE THREAD

**Issue by jaagupku** [terrestris/react-geo#2753]
https://terrestris.github.io/react-geo/docs/latest/index.html#!/WfsSearch

Example on that page is broken. Property `maxFeatures` must be specified, otherwise it sets it to `0` and WFS failes to parse that.
That example is missing `maxFeatures` property and is broken.

**Comment by dnlkoch** [comment]
Thanks for you report @jaagupku. 

I can reproduce the issue und the example is actually broken.
