### ISSUE TITLE
[Feature]: Move functionality unrelated to react to better suited libraries

### ISSUE THREAD

**Issue by marcjansen** [terrestris/react-geo#2923]
### Related issue

This was raised by @KaiVolland in https://github.com/terrestris/react-geo/pull/2921#issuecomment-1291685212.

List of candidates and where they might live better:

* `src/Util/typeUtils.spec.tsx` => move to https://github.com/terrestris/ol-util (should probably wait unti https://github.com/terrestris/ol-util/pull/826 is merged, then that library has moved to TypeScript)

Please add more candidates as you find them.

### Feature request

See above, move code where it fits best.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by weskamm** [comment]
Fixed via https://github.com/terrestris/ol-util/pull/953

Will be visible after we are ready to update ol-util (to 10.2.3) again, see #3109
