### ISSUE TITLE
[Question]: OpenLayers 7

### ISSUE THREAD

**Issue by digoburigo** [terrestris/react-geo#2963]
### Your question

There is a plan to upgrade to OpenLayers 7?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by digoburigo** [comment]
Oh ok, thanks for the info! Feel free to close this issue if necessary

**Comment by annarieger** [comment]
See https://github.com/terrestris/react-geo/pull/2972

**Comment by annarieger** [comment]
Hi @digoburigo!

The new react-geo version v20.0.0(https://github.com/terrestris/react-geo/releases/tag/v20.0.0) which includes upgrade to OpenLayers 7 among other things, is released just now.

Please check and enjoy :)
