### ISSUE TITLE
[Bug]: In readme, the examples and tutorial links are broken.

### ISSUE THREAD

**Issue by gisfinder** [terrestris/react-geo#3047]
### Current Behavior

the links are broken.

### Expected Behavior

to link the related document

### Steps To Reproduce

check the read me document links of "example" and "tutorial".

### Version

16.2.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gisfinder** [comment]
Now the broken links are recovered.

**Comment by LukasLohoff** [comment]
Thanks for the report anyway. I'll close this issue
