### ISSUE TITLE
dead link to Docs on gh-pages github.io doc site

### ISSUE THREAD

**Issue by justb4** [terrestris/react-geo#326]
The page
https://terrestris.github.io/react-geo/ gives a dead link (https://terrestris.github.io/react-geo/docs/react-geo/0.1.1/index.html) for Docs, old version.

IMO Docs must refer to
https://terrestris.github.io/react-geo/docs/%40terrestris/react-geo/1.3.0/index.html

**Comment by marcjansen** [comment]
Thanks for the report, issue confirmed.

**Comment by dnlkoch** [comment]
Thanks again for the report, fixed in #329.
