### ISSUE TITLE
Featurelist up-to-date?

### ISSUE THREAD

**Issue by tilladams** [terrestris/react-geo#395]
Dear Kai, @react-geo-Team,

having a look at the feature list in the WIKI looks like it is not up to date:
https://github.com/terrestris/react-geo/wiki/Feature-List

Perhaps we can keep this list up to date and write above, for which version the list was lastly updated

**Comment by KaiVolland** [comment]
The FeatureList is "almost" up to date. But ill add the last update version to the title.

I'll update it now with the latest features.

Every included feature has the id of its PullRequest beside (#Something) and the release version it was introduced in **bold**.

**Comment by tilladams** [comment]
perfect! Thanks!
