### ISSUE TITLE
Split Digitize Button

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#475]
We should split the `DigitzeButton` into multiple `buttons`.

At least into `DrawButton` and `ModifyButton`, `CopyButton` and `DeleteButton`.

~~It also contains a prop named `style` which is allready reserverd for css inline-styles. It should be removed. See https://github.com/terrestris/react-geo/blob/master/src/Button/DigitizeButton/DigitizeButton.jsx#L289~~

**Comment by marcjansen** [comment]
Is this still relevant?
