### ISSUE TITLE
Homepage: Links to 'Examples' and 'Docs' are broken because they miss the path-segment 'react-geo'

### ISSUE THREAD

**Issue by marcjansen** [terrestris/react-geo#484]
Title basically says it all:

Examples link to

`https://terrestris.github.io/docs/@terrestris/react-geo/5.5.0/index.html`

instead of 

`https://terrestris.github.io/react-geo/docs/@terrestris/react-geo/5.5.0/index.html` 

Same for docs.

**Comment by dnlkoch** [comment]
Closed via #486.
