### ISSUE TITLE
Icons not showing in online examples / fonts not published?

### ISSUE THREAD

**Issue by marcjansen** [terrestris/react-geo#488]
This is how the [circle-menu example](https://terrestris.github.io/react-geo/examples/CircleMenu/CircleMenu.example.html) renders for me:

![image](https://user-images.githubusercontent.com/227934/37458847-91c32d2a-2846-11e8-8a30-821a388835ca.png)

The console shows that the fonts didn't load properly.

**Comment by dnlkoch** [comment]
Fixed via #504.
