### ISSUE TITLE
Enhance the setup docs -> canvas

### ISSUE THREAD

**Issue by weskamm** [terrestris/react-geo#511]
I tried to get the Tests running on a Xubuntu machine, but all tests failed with a "canvas of null" error.
Solution for me was to replace `canvas-prebuilt` with `canvas` in package.json and then do an "npm i"
```
-    "canvas-prebuilt": "1.6.5-prerelease.1",
+    "canvas": "1.6.9",
```
We should investigate why the prebuilt version behaves this way...

**Comment by KaiVolland** [comment]
You could open a PR with your change. If travis is ok with it we could just replace this package.
