### ISSUE TITLE
Remove Codacy

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#519]
This app has no benefit for this project. Plz disable @marcjansen

**Comment by dnlkoch** [comment]
I removed the `codacy` webhooks from this project and hopefully this helps…

**Comment by KaiVolland** [comment]
Sadly it didn't new PRs (from greenkeeper) are still checked by codacy... WHATTAFAK

**Comment by marcjansen** [comment]
Confirming that for certain PRs codacy still does something. I have just revoked any permissions and even deleted my account over there. Still hoping this did the trick.

**Comment by dnlkoch** [comment]
Opening a codacy report shows (at least for me), that the check was performed for `hwbllmnn/react-geo`. 

@hwbllmnn Could you please check, if you can disable this project in your codacy settings?

**Comment by dnlkoch** [comment]
It think actually defeated it…
