### ISSUE TITLE
Find more common name for Titlebar

### ISSUE THREAD

**Issue by annarieger** [terrestris/react-geo#537]
A `Titlebar` component can be used not only in component header but also be placed somewhere else (e.g. as component footer) so we probably need less confusing name for it (something like `HeaderOrFooterBar`?)

**Comment by marcjansen** [comment]
How about `Bar` or `SideBar`? These also would imply (to me) that they would also work if placed to either the right or left side. Thinking out loud here.

**Comment by KaiVolland** [comment]
IMHO the name is pretty ok as it is is a bar that contains a title. There is nothing specfic about its location – even if a title is mostly at the top. You don't even have to put it in the "footer" or "header". "Bar" sounds quite unprecise and "SideBar" includes a location.

**Comment by marcjansen** [comment]
Agreed, let's close this issue.
