### ISSUE TITLE
Folder Structure refactoring

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#56]
I'd like to refactor the Folder structure for `Util` and `VisibleComponent`.

1. Every Util should have its own Folder where its `*.js` and `*.spec.js` lives. Just like we have it with the components. -> ~~We should rename `TestUtils` to `TestUtil` if we're on the way.~~ solved with #61 
2. I'd like to introduce a `HOC` folder that would contain the `VisibleComponent`.

**Comment by marcjansen** [comment]
> We should rename TestUtils to TestUtil if we're on the way.
See #61
