### ISSUE TITLE
Refactor ToggleButton/ToggleGroup/SimpleButton

### ISSUE THREAD

**Issue by dnlkoch** [terrestris/react-geo#613]
The `ToggleButton` component has been adjusted several times and even if this components seems to be very ordinary, we're still facing issues (e.g. #605).

Therefore I suggest to rewrite the component by checking if we really need a separate `SimpleButton` and `ToggleButton` and how we could avoid or at least improve the usage of the `ToggleGroup`.

**Comment by marcjansen** [comment]
#605 is closed, can this be closed as well?
