### ISSUE TITLE
WfsSearch - buggy response handling

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#621]
Implement mechanism to abort pending requests or ensure that the repsonse of the latest request will be shown.

e.g.
When searching for alabama:

Typing: `ala` --> requests is send, finds 999999 features and takes 5 seconds
Typing: `alab` --> request is send, finds 200 features and takes 1 second

The more precise requests is returned before the unprecise one.... and so the unprecise results will be shown after 5 seconds even if the precise result was already shown.

**Comment by marcjansen** [comment]
no `fetch` then, right?

**Comment by hwbllmnn** [comment]
IMO, two things would alleviate the issue:

* a delay of a few hundred ms before actually sending the search request, cancelling any pending requests that have not fired yet (not sure if this exists yet)
* augmenting the mechanism with an ordering count, discarding the responses of obsolete requests

I'll probably tackle this tomorrow, if nothing else comes up.

**Comment by KaiVolland** [comment]
Fixed with #622
