### ISSUE TITLE
Usage of outdated ReactJS lifecycle methods

### ISSUE THREAD

**Issue by dnlkoch** [terrestris/react-geo#648]
Some ReactJS lifecycle methods (`componentWillMount()`, `componentWillReceiveProps()` and `componentWillUpdate()`) will be removed in version 17.

We should fix the usage of the deprecated methods listed above by either refactoring the classes by using the newly introduced static methods, e.g. ` getDerivedStateFromProps()` (see [here](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops)) or adjusting the deprecated methods with the `UNSAFE_` prefix (see [here](https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles)).

I'm pro option one.

See failing build in #647 as well.

**Comment by ahennr** [comment]
In this context we should double-check for our components if `shouldComponentUpdate` or `React.PureComponent` can be used more often. This would increase performance significantly (especially in IE11)

**Comment by dnlkoch** [comment]
@ahennr Absolutely! Pure! Pure! Pure! 

Could you please create an issue for this?

**Comment by ahennr** [comment]
See https://github.com/terrestris/react-geo/issues/650

**Comment by dnlkoch** [comment]
Closed via #663.
