### ISSUE TITLE
Unify method declaration

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#65]
The declaration of class methods should be unified:

GOOD:
```javascript
  getLegendUrl() {
    […]
  }
```
BAD:
```javascript
  getLegendUrl = () => {
    […]
  }
```

Use `.bind()` when scope is wrong.

**Comment by marcjansen** [comment]
Will fix this.

**Comment by KaiVolland** [comment]
As i know now we should not insist in using the on or the other way of method declaration.

**Comment by marcjansen** [comment]
I want to add that I personally favor the original `GOOD` over our current mixed state. But this is just me.
