### ISSUE TITLE
Handle inefficiency of Webpack's Treeshaking 

### ISSUE THREAD

**Issue by amir-ba** [terrestris/react-geo#652]
Since the `dist` version of `react-geo` is in `CommonJS`, `Webpack`  can't be smart enough to only load the imported parts of the code.  I would suggest that we compile the library into two folders. Where one folder uses CJS  and the other folder uses ES5 modules and in the `Package.json` we will have the `main` field point to the CJS version and the `module`  plus the `jsnext:main` point to the ES5 folder.  
This is at least what others like `Redux`  and `antd` are doing.

**Comment by marcjansen** [comment]
If this is easily doable, I am plus one, but would favor feedback of more developers here.

Can we alternatively just publish Ecmascript modules and tell people how to achieve backwards compatibility in their apps? We only ever use the es modules syntax, and we have babel in in our projects, which handles the transpiling for us in our projects. @weskamm may want to weigh in here.

**Comment by weskamm** [comment]
Right, the problem should also be solved by removing babel from react-geo, as its a library and not an application.
The application that uses react-geo should make use of babel, if needed.
Thoughts @dnlkoch @KaiVolland ?

**Comment by amir-ba** [comment]
@marcjansen if we have both Ecmascript and CommonJS code there we also have to set the `sideEffect` tag in the `package.json` file to false. This will tell `webpack` (V4 and above) to turn:
import { a, b } from "big-module-with-flag" to import { a } from "big-module-with-flag/a"; import { b } from "big-module-with-flag/b".

**Comment by dnlkoch** [comment]
Thanks @amir-ba for your well reported analysis of the issue and as far as I can see, the export of `CJS`   code and `ES6` modules looks very promising.

:+1:

**Comment by marcjansen** [comment]
Hrm, is this still relevant? I don't think so.

**Comment by dnlkoch** [comment]
I will close this one, but please have in mind, that we aren't publishing the ES6 modules at the moment.
