### ISSUE TITLE
Can we optimize import of antd when testing, become faster and get rid of annoying warning?

### ISSUE THREAD

**Issue by marcjansen** [terrestris/react-geo#653]
`npm test` yields many of the following warnings when running the tests.

```
 PASS  src/Button/SimpleButton/SimpleButton.spec.jsx
  ● Console

    console.warn node_modules/antd/lib/index.js:499
      You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.
```

It would be nice if we could
* optimize the import when testing as suggested,
* become faster while doing that,
* and get rid of this annoying message

Can we do all of the above?

**Comment by marcjansen** [comment]
Ping @weskamm? Maybe the things you worked on today are related.

**Comment by weskamm** [comment]
Not sure what your setup looks like, but i dont get these warnings on current master and the plugin you mentioned is contained in package.json for at least half a year?

**Comment by marcjansen** [comment]
I will retry later.

**Comment by dnlkoch** [comment]
I can't reproduce the specified behaviour either.

@marcjansen Do you still get the message with the current master?

**Comment by marcjansen** [comment]
I didn't test it, tbh. sorry. Let's close this and reopen if necessary.
