### ISSUE TITLE
Documentation / Examples too large, breaks on some mobiles

### ISSUE THREAD

**Issue by weskamm** [terrestris/react-geo#697]
https://terrestris.github.io/react-geo/docs/latest/index.html

loads 11,5 MB and triggers 222 requests on page load.
Apple iPad mini Safari browser breaks, as its too huge.
Besides, the layout / menu is not visible on mobile (android chrome).

Maybe we can introduce some kind of lazy loading / initial collpased state of all examples?

**Comment by marcjansen** [comment]
Yes please, also I'd find it nice if it didn't directly scroll over to the Ujah-image. Can we not create many single pages for all the components?

**Comment by marcjansen** [comment]
What should we do here?

**Comment by dnlkoch** [comment]
We should give [pagePerSelection](https://react-styleguidist.js.org/docs/configuration.html#pagepersection) a try at least.

**Comment by weskamm** [comment]
fixed by Unraveler, thanks!
