### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#757]
The following examples are broken. We should check these and make the needed adjustments/fixes:

- MeasureButton
- ToggleGroup
- AddWmsPanel (window not closable)
- FeatureGrid (remote feature grid filter is broken)
- DropTargetMap
- LoadifyComponent (dragging not possible, LoadingMask not on Tree)
- Legend (Layer States (USA) with "extraParams": broken)

**Comment by annarieger** [comment]
Both window examples are broken / behave not properly as well:
* both windows cannot be dragged
* window cannot be closed on `Esc` click (2. example)

**Comment by KaiVolland** [comment]
@annarieger 
the dragging should be fixed in 8.10.2
the window needs to be focused to be closable with Esc

**Comment by KaiVolland** [comment]
ToggleGroup example should be fixed with: https://github.com/terrestris/react-geo/pull/772

**Comment by marcjansen** [comment]
Let's close this for now. If there are still issues, create new reports.
