### ISSUE TITLE
Standalone utility packages

### ISSUE THREAD

**Issue by jansule** [terrestris/react-geo#762]
With regard to creating standalone utility packages out of `react-geo/src/Util/`-modules, does it make sense to group different modules into one npm package? My approach would be to group all `base utilities` into one package and all `openLayers` related utilities into another one. 

The result would be following packages:

1. @terrestris/base-util
    - CsrfUtil
    - MathUtil
    - ObjectUtil
    - StringUtil
    - UndoUtil
    - UrlUtil
    - Logger
2. @terrestris/ol-util
    - AnimateUtil
    - CapabilitiesUtil
    - FeatureUtil
    - FileUtil
    - GeometryUtil
    - MapUtil
    - MeasureUtil
    - ProjectionUtil
    - WfsFilterUtil

Furthermore, should the modules also be converted into ES5 for compatibility reasons?
@terrestris/devs

**Comment by amir-ba** [comment]
@jansule this is a great idea and thanks for being the one that makes this finally happen :D. 
I think 2 libraries makes sense. Maybe we could also have a` Shogun-utils` libraries as well later on. 
Regarding the ES5 compilation I would suggest we have the libraries in both ES5 and ES6 so we can later also release an ES6 version of `react-geo`.

**Comment by weskamm** [comment]
absolutely +1 @amir-ba !

**Comment by amir-ba** [comment]
And while you are at it @jansule it might be good to see if you can export `react-geo` with additional

**Comment by jansule** [comment]
So far, only ES6 versions of both packages were published. @terrestris/devs do you think ES5 versions will be necessary? As far as I understand, the packages will be mainly used by us, usually using ES6. The only working solution for publishing both versions (I found so far) would result in publishing two additional packages, which might be a little over the top.

**Comment by KaiVolland** [comment]
I'm ok with just publishing as ES6. Just works fine in every WebPack environment. If we want to support the use of the util packages in other environments (node) we can still think about that issue...

**Comment by weskamm** [comment]
Ok, i will check if treeshaking works well with this approach, but it may be that we need to tag the package as `module` in the packge.json. If problems arise, i will open up PRs or issues. Will close this now
