### ISSUE TITLE
Unused prop 'closable' in Panel

### ISSUE THREAD

**Issue by jgrieb** [terrestris/react-geo#805]
In Panel.jsx there is a prop 'closable' defined, but not used. In #379 it looks like all 'closable' should be removed. So is this a relict that can simply be deleted or is there something planned with this prop?

**Comment by dnlkoch** [comment]
Nice catch @jgrieb!

I'm +1 for removing the prop `closable`. Could you provide a PR regarding to this?

**Comment by jgrieb** [comment]
See #806
