### ISSUE TITLE
Computation of default panel/window position is weird since rnd update to version 8+

### ISSUE THREAD

**Issue by annarieger** [terrestris/react-geo#812]
Steps to reproduce:

* Create and render some panel or window component like this:
```javascript
<Window
  parentId="parentId"
  title="title"
  width={300}
  height={150}
  x={100}
  y={100}              
 >
   <div>test</div>
  </Window>
```
* Window is expected to appear at (100, 100) in browser
* As the matter of fact the rendered window is shown at (200, 200)
  * CSS inspector shows the following rule for the `react-geo-panel` div:
```css
 transform: translate(200px, 200px)
```
So the real translation is actually doubled and the rendered component is shown not there where expected..

A quick fix for window example was introduced in #811, but it cannot be a permanent solution..

This weird behaviour will be observed since major update of `rnd` package from 7.4.3 to 8.0.x and is (probably!) related to [these](https://github.com/bokuweb/react-rnd/commit/27ef1f066f28ca5981fb2696b5aabae009fecfd5) changes.

**Comment by marcjansen** [comment]
This is very annoying and most probably still in here. What can we do about this?

**Comment by weskamm** [comment]
At least in this example it works:
https://codesandbox.io/s/my4kjly94x
Maybe the problem is on our side? I dont see a current issue in their repo for this.
Their example is using a `display: flex` style..
Here is my fiddle trying to reproduce / fix the issue (could not get it working due to dependency problems, maybe someone else can get it work):
https://codesandbox.io/s/j4knnj8p0v

**Comment by KaiVolland** [comment]
I did find the code in react-rnd which causes this buggy behaviour. It's [here](https://github.com/bokuweb/react-rnd/blob/master/src/index.tsx#L248) where the state of a referenced child is updated in `componentDidMount`. I guess this breaks the react-lifecycle and leads to a doubled calculation of the css-transformation in [react-draggable](https://github.com/STRML/react-draggable/blob/master/lib/Draggable.js#L371). 
Not sure how to deal with this.
