### ISSUE TITLE
[question] workshop tutorial failed

### ISSUE THREAD

**Issue by zuhrasofyan** [terrestris/react-geo#838]
Guten Tag!

I followed the workshop instruction (https://terrestris.github.io/react-geo-ws/first-steps/) to bootstrap `react-geo` based app using `create-react-app`.
Unfortunately, the app failed miserably when I add `react-geo` dependency.

```
 sh: react-scripts: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! my-app@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the my-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

 It seems the react-geo is not compatible with the new react (16.4.2) release? I had to lower react and react-dom version to be able to run it. but again, the installation dependency of `antd` and `ol` do have another problem when I start the app:

```
./node_modules/@terrestris/ol-util/src/MapUtil/MapUtil.js
Module parse failed: Unexpected token (153:25)
You may need an appropriate loader to handle this file type.
|    * @return {ol.layer.Layer} The layer.
|    */
|   static getLayerByOlUid = (map, ol_uid) => {
|     const layers = MapUtil.getAllLayers(map);
|     const layer = layers.find((l) => {
```
So, is the workshop outdated, or there is some correct way to setup react-geo based app that I have not do?

**Comment by dnlkoch** [comment]
Thanks for your report @zuhrasofyan!

The workshop is indeed a bit outdated and hasn't been tested with the newer versions (especially with the latest release) of `react-geo` for a while, but should work with the latest `react` at least.

Could you please check if the workshop is working with version 8 by changing it's version to `8.12.1`? Taking a quick glance, this worked for me.

**Comment by marcjansen** [comment]
Any chance you might dig deeper and fix the root error? Or upgrade the workshop? That would be much appreciated.

**Comment by hwbllmnn** [comment]
Might be unrelated, but I had a similar phenomenon using npm once. After installing a new package with `npm install --save <package>`, npm would remove some other packages. Just running `npm install` again reinstalled them. Perhaps this happens with a certain combination of dependencies?

**Comment by PeterC66** [comment]
I get the same error message when at the Include a react-geo component of the workshop.

I first noticed it when trying to implement react-geo into an existing test react/ node system. Not being able to solve the issue there, I started a new project and followed the workshop instructions exactly - and got the same Module parse error. 

I am not very familiar with all the technology and versions. What do I do to get it working?

**Comment by PeterC66** [comment]
Yes thanks.

**Comment by KaiVolland** [comment]
@zuhrasofyan can this be closed or do you have further problems?

**Comment by zuhrasofyan** [comment]
Sorry.. Will close the issue now.
