### ISSUE TITLE
Corrections to docs/latest

### ISSUE THREAD

**Issue by PeterC66** [terrestris/react-geo#861]
On working through [docs/latest](https://terrestris.github.io/react-geo/docs/latest/) with Chrome I noticed the following

--------------
On opening, in the console
```
bundle.7c4a829b.js:790 TypeError: Cannot read property 'objectToRequestString' of undefined
    at RemoteFeatureGrid.fetchData (eval at evalInContext (bundle.7c4a829b.js:48), <anonymous>:91:25)
    at RemoteFeatureGrid.componentDidMount (eval at evalInContext (bundle.7c4a829b.js:48), <anonymous>:51:10)
[...]
bundle.7c4a829b.js:942 TypeError: Cannot read property 'objectToRequestString' of undefined
    at RemoteFeatureGrid.fetchData (eval at evalInContext (bundle.7c4a829b.js:48), <anonymous>:91:25)
    at RemoteFeatureGrid.componentDidMount (eval at evalInContext (bundle.7c4a829b.js:48), <anonymous>:51:10)
[...]
```

----------------
Under addwmspanel clicking on `Fetch capabilities of OWS terrestris`  in the example results in the console message
```
bundle.28a45fe4.js:790 Uncaught TypeError: Cannot read property 'parseWmsCapabilities' of undefined
    at AddWmsPanelExample.onClick (eval at evalInContext (bundle.28a45fe4.js:48), <anonymous>:55:22)
[...]
```
---------------
Under wfssearch the reference to https://openlayers.org/en/latest/apidoc/ol.format.WFS.html#writeGetFeature is broken
I think it should be to
https://openlayers.org/en/latest/apidoc/module-ol_format_WFS.html

---------------
In featuregrid the last example (with a remote feature source) shows
`TypeError: Cannot read property 'objectToRequestString' of undefined`

----------
In propertygrid `Class representing a fature grid`  it should be `feature` 

---
Under panel the last example seems empty - it looks like it is offset. If this is the intention maybe a comment to this effect might help us see it?
Also the text is `Intial size (673 * 134)`  and presumably it should be `Initial`

---
the #map link goes to the wrong place

**Comment by KaiVolland** [comment]
Thanks for the report @PeterC66.

**Comment by KaiVolland** [comment]
Just to let you know. PRs are very welcome. So if you know how to fix a bug/issue… keep them coming. :v:

**Comment by PeterC66** [comment]
Thanks, but I am very new to all this (git, npm etc) so I will have to learn how to do a PR.
I do like react-geo and am beginning to work on using it in my application (a refactoring of my existing OpenLayers 4 system at bit.ly/M4OPS into a MERN stack).
