### ISSUE TITLE
Add further examples for `WfsSearchInput` component

### ISSUE THREAD

**Issue by annarieger** [terrestris/react-geo#881]
At the moment there is an example showing usage of `WfsSearchInput` component with `AgFeatureGrid`.

In some another project a much more complex solution showing results sorted by requested featureTypes was developed. This should be ported to `react-geo` as well:

![image](https://user-images.githubusercontent.com/3939355/45609280-95073a00-ba57-11e8-99e5-8503d2f1cee5.png)

**Comment by marcjansen** [comment]
This would be much appreciated!

**Comment by dnlkoch** [comment]
Ping @annarieger.

**Comment by hwbllmnn** [comment]
In #2652 a search results panel has been introduced that can be used with WFS, solr or other searches to display categorized results.

**Comment by annarieger** [comment]
Done with #2652
