### ISSUE TITLE
Some references to the openlayers.org/en/latest/apidoc in code comments are broken

### ISSUE THREAD

**Issue by PeterC66** [terrestris/react-geo#882]
This is just about the comments in some code, so only relevant to those looking at the internals. It seems that the OL team have changed how they reference their apidocs.

I started to try changing the code and do a PR myself, but maybe it is not so simple. Maybe the references should be to the specific relevant version of ol rather than the **latest**, to avoid things being out of step?  For example in the comments below about events there are several areas where the code and comments do not seem to tie up with the latest apidoc. Note that I have not looked in detail at the coding issues, just the broken links.

In **DigitizeButton.jsx**

https://openlayers.org/en/latest/apidoc/ol.interaction.Draw.Event.html
should be
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-DrawEvent.html

https://openlayers.org/en/latest/apidoc/ol.interaction.Modify.Event.html
maybe should be
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Modify-ModifyEvent.html
but the modifystart and modifyend events are not mentioned anywhere.

https://openlayers.org/en/latest/apidoc/ol.interaction.Translate.Event.html
maybe should be
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Translate-TranslateEvent.html
but the translatestart, translateend and translating events are not mentioned anywhere.

https://openlayers.org/en/latest/apidoc/ol.interaction.Select.Event.html
maybe should be
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select-SelectEvent.html
but the select event is not mentioned anywhere.

https://openlayers.org/en/latest/apidoc/ol.interaction.Draw.html
should be
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html

https://openlayers.org/en/latest/apidoc/ol.interaction.Modify.html
should be
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Modify-Modify.html

https://openlayers.org/en/latest/apidoc/ol.interaction.Translate.html
should be
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Translate-Translate.html

https://openlayers.org/en/latest/apidoc/ol.interaction.Select.html
should be
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select-Select.html

In **ZoomToExtentButton.jsx**
https://openlayers.org/en/latest/apidoc/ol.View.html#fit
should be
https://openlayers.org/en/latest/apidoc/module-ol_View-View.html#fit

In **WfsSearch.jsx**
https://openlayers.org/en/latest/apidoc/ol.format.filter.html
should presumably be
https://openlayers.org/en/latest/apidoc/module-ol_format_filter.html

https://openlayers.org/en/latest/apidoc/ol.format.WFS.html
should be
https://openlayers.org/en/latest/apidoc/module-ol_format_WFS.html

**Comment by marcjansen** [comment]
Thanks for the ticket. 

Since OpenLayers moves fast and we try to stay in sync with their pace, I'd favor using links to latest, thes may outdate just as well as specific versions.

wrt how to create a PR, I'll provide some hints, since this a good starting point for first-time committers.

**Comment by PeterC66** [comment]
Thanks.  I'd be happy to have a go at a PR if you give me some guidance. If it is relevant, I use VSCode.

**Comment by marcjansen** [comment]
Ok, here we go:

Generally:

1. First, [fork terrestris/react-geo](https://github.com/terrestris/react-geo/fork "… fork to create a copy of react-geo whith which you can do what you want"),
2. clone the fork on your local computer: `git clone https://github.com/PeterC66/react-geo`
3. go into the created repo: `cd react-geo`
4. Create and select a new branch `git checkout -b apidoc-fixes`
5. Edit code whith whatever editor suits you best
6. See which files you have changed: `git status`
7. See what exactly you have changed: `git diff` (Quit the output by hitting`q`)
8. Add and commit code to your local branch `git add path/to/changed/file` & `git commit -m"My commit message"`
9. Push the local branch with your changes to your fork on github: `git push origin apidoc-fixes`
10. Visit https://github.com/terrestris/react-geo, than the GUI will help you create a pull request.

If you ever want to update your local repo with changes over at the terrestris/react-geo repo do as follows:

1. (Once) Add a remote named upstream that points to terrestris/react-geo `git remote add upstream https://github.com/terrestris/react-geo.git`
2. on the branch you want to update: `git pull upstream master`

HTH.

**Comment by marcjansen** [comment]
Can we close this now?

**Comment by PeterC66** [comment]
Yes, as far as I am concerned.
