### ISSUE TITLE
Clarify the MapProvider and MappifiedComponent structure in the documentation

### ISSUE THREAD

**Issue by PeterC66** [terrestris/react-geo#883]
I am trying to understand the MapProvider and MappifiedComponent structure. This is feedback on the documentation/workshop about them, and may reflect as much my limited understanding.

It seems to me that (WRONG - see Update below), put simply, the MapProvider puts the olMap in a MapComponent within it into the React context, and any MappifiedComponent has access to that olMap as a prop. Is that it?

The documentation about this has confused me.

- There is no mention of MapProvider as a component in its own right in https://terrestris.github.io/react-geo/docs/latest/index.html
- The documentation of MappifiedComponent there is minimal.
- MapProvider is mentioned in the MapComponent example, but it would have helped my initial understanding if it were not mentioned there, as in the workshop example https://terrestris.github.io/react-geo-ws/map-integration/map-component.html.
- Better to have a separate example showing the MapProvider and a MappifiedComponent, as there is little sense showing one without the other. 
- In the workshop the mappify function is mentioned but not the MappifiedComponent, which is presumably the newer way to use it. Which should I be using now (eg will mappify be deprecated)? [ Update: Maybe I have misunderstood totally - is MappifiedComponent just a generic term for a component that has been returned by mappify, and not a tag we would use literally?]
- (Ignore this - see Update below) Given my simple understanding I don't see why there is a `const Map = mappify(MapComponent);` line in the workshop. Why mappify the MapComponent, if it is within a MapProvider?
- There is no mention of this specifically but is it true that MapProvider/MappifiedComponent are only able to cope with a single olMap in an application? This means that, if I have two maps (eg side by side) that I need to handle, I need to find a different approach?

Lastly on the general concept, I have been getting to know Redux and encouraged to use that, rather than context, for storing state. This will be more relevant as I later develop some of the feature handling aspects of my system. Does this affect how I should use MapProvider and MappifiedComponent?

Update
I have re-read the code in https://terrestris.github.io/react-geo/docs/latest/index.html#mapcomponent. This initially confused me because I am not yet comfortable with promises, but it has helped me see that my initial 'put simply' is wrong. 

My latest version is that the MapProvider puts the olMap it is given into the React context, and any component (including a MapComponent) that wants access to this olMap has to be transformed by the mappify function, and then the returned 'mappified component' has access to that olMap as a prop. Is that nearer?

Sorry if this is all my misunderstanding - and thanks for not only a useful package but also excellent examples of programming.

**Comment by PeterC66** [comment]
My confusion indicated in my ticket above is still valid.  However I think I am now understanding the underlying principles better. I don't think I shall use the MapProvider and mappify, as I have developed a similar functionailty (with simple HOCs) using the Redux store to access all sorts of data, which fits in better with my other needs.

**Comment by marcjansen** [comment]
There is no need to use MapProvider and the mappify-HOC, they might come in handy once you want to pass the map to several usually independent components.

**Comment by PeterC66** [comment]
After further exploration with my (quite complicated) mapping system I realise that I made a big mistake putting the OL map into the Redux store, as it needs to be manipulated in other ways than the Action-Reducer cycle. So I am back to using MapProvider and mappify, and will see how I get on. A lot of my other data will still be handled by Redux.

**Comment by marcjansen** [comment]
This sounds like the way we do use redux and the HOC.

**Comment by PeterC66** [comment]
Don't MapProvider and mappify use React context rather than Redux?

**Comment by marcjansen** [comment]
They do, I was talking about applications we build.

**Comment by PeterC66** [comment]
Thanks for all your help, I have appreciated what you are doing.

However I shall drop out of these conversations because I have switched from using React with react-geo to Vue.js with vuelayers.  I wish you all the best.

**Comment by marcjansen** [comment]
Bye then, thanks for the feedback. Perhaps you'll come back anytime in the future. All the best to you as well.
