### ISSUE TITLE
Using react-geo with create-react-app

### ISSUE THREAD

**Issue by PeterC66** [terrestris/react-geo#915]
As I understand it the react-geo workshop currently only runs with react-geo version 8 or smaller as 
> create-react-app does not support ES6 dependencies

In developing my own React/Redux/ react-geo application I have started with create-react-app, and stayed with react-geo v 8 because I assumed I needed to.

I would prefer to use the latest version of react-geo (and antd), and have seen the possibility of ejecting, and suggestions [like this](https://stackoverflow.com/questions/42942000/using-create-react-app-and-having-es6-dependencies).

I am not sure where to find recommendations about versions and dependencies in the documentation - although I have looked in the various package.json files.

What do you recommend?

**Comment by PeterC66** [comment]
Since asking the above I have just heard that Create React App 2.0 has been released, and I have updated my app to "react-scripts": "2.0.3". I will explore what the effect of this is, but any advice welcome on updating to react-geo v10.

**Comment by marcjansen** [comment]
Updating shouldn't be problematic. Can you confirm?

**Comment by PeterC66** [comment]
Sorry I can't as I am no longer using react-geo.

**Comment by marcjansen** [comment]
Ok thanks for the feedback. Hope to see you again in the future.
