### ISSUE TITLE
Please don’t publish experimental syntax on npm

### ISSUE THREAD

**Issue by xersist** [terrestris/react-geo#933]
Hi I'm been searching for an issue about a syntax error in the MathUtil.js file about Support for the experimental syntax 'classProperties' isn't currently enabled. I'm using the CRA 2 and Dan Abramov makes a good argument about libraries publishing experimental syntax. Please see following post.

[material-components/material-components-web-react#107(comment)](https://github.com/material-components/material-components-web-react/issues/107)

Thanks!

**Comment by marcjansen** [comment]
Thanks for the feedback. We'll probably consider transpiling the code to sth. more generally usable as a second option.

**Comment by marcjansen** [comment]
@xersist can you confirm everything is working for you? TIA

**Comment by dnlkoch** [comment]
The latest version (10.4.1) has just been released and contains the appropriate fix.
