### ISSUE TITLE
Vectortile layer support

### ISSUE THREAD

**Issue by moonlightgis** [terrestris/react-geo#953]
Hello we are help you to contribute this project.
I will making component for react-geo to support vectortile (pbf)  layers.

- Render VectorTile 
- Vectortile Styling based on Mapbox style.

**Comment by KaiVolland** [comment]
Thanks for your will to help, but as `react-geo` is based on OpenLayers – which already supports [VectorTile rendering](http://openlayers.org/en/v4.6.5/apidoc/ol.VectorTile.html) – I'm not sure what your contribution would look like.
The styling of layers is also handled by OpenLayers.

**Comment by KaiVolland** [comment]
Closed due to inactivity.
